import React, { useState } from "react";
import Box from "@material-ui/core/Box";
import nftImg from "../../assets/BuyPage/Rectangle 66.png";
import Typography from "@material-ui/core/Typography";
import BuyBidRentButton from "../Buttons/BuyBidRentButton/Index";
import CreatorCollector from "../CreatorCollector/Index";
import { makeStyles } from "@material-ui/core";
import BidPageTabs from "../BidTabs/Index";
////////////////////////// Dummy description start ////////////////////////////////////////
const loremDescription =
  "Original AI Art Video Interpolation movie by Artificial Paintings AI model. This video captures the process of generating pictures by artificial intelligence.You will own a 100% unique collector’s item   that nobody else in the world will ever have. The purchase includes:   Original MP4 file 1024x1024px, which was generated by AI; Transfer of   all intellectual rights to use and distribute the video for any   purpose. Limited edition";
////////////////////////// Dummy description end   ///////////////////////////////////////

const BuyPageSection = ({
  nftImage = `${nftImg}`,
  nftitle = "Art Name",
  quality = "10",
  timer,
  description = `${loremDescription}`,
  button = "buy",
}) => {
  const classes = useStyles();
  const [load, setLoad] = useState(true);

  const handleClick = () => {
    setLoad(!load);
  };

  return (
    <Box className={classes.nft_buyPage_main}>
      <Box className={classes.nft_img_div}>
        <img src={nftImage} alt="img" />
      </Box>
      <Box className={classes.nft_details_div}>
        <Typography className={classes.buyNft_title} variant="h2">
          {nftitle}
        </Typography>
        <Typography className={classes.buyNft_description} variant="h5">
          Description
        </Typography>
        <Typography className={classes.buyNft_description_para} variant="p">
          {load === false ? description.slice(0, 10) : description}
          <br></br>
          {load === false ? (
            <Typography className={classes.ShowMore_link} onClick={handleClick}>
              show more
            </Typography>
          ) : (
            <Typography className={classes.ShowMore_link} onClick={handleClick}>
              Show less
            </Typography>
          )}
        </Typography>
        <Box className={classes.buypage_quantity}>
          <Typography className={classes.buypage_quan_cont} variant="h5">
            QUANTITY
          </Typography>
          <Typography className={classes.buypage_quan_cont} variant="h5">
            {/*//////////////////////  Nft Quantity  //////////////////////////  */}
            {quality}
          </Typography>
        </Box>
        <Box className={classes.timer}>
          {/*////////////////////////   Nft CountDown Timer //////////////////////*/}
          {timer}
        </Box>
        <Box>
          {/* ////////////////////////// Bid Button  ////////////////////////// */}
          <BuyBidRentButton buttonContant={button} />
        </Box>
        <Box>
          <CreatorCollector />
        </Box>
        <Box>
          <BidPageTabs />
          <hr></hr>
        </Box>
      </Box>
    </Box>
  );
};

export default BuyPageSection;

const useStyles = makeStyles((theme) => ({
  nft_buyPage_main: {
    display: "flex",
    justifyContent: "center",
    gap: "45.02px",
    padding: "70px",
    background: theme.palette.background.default,
    color: theme.palette.text.primary,
    fontFamily: theme.typography.fontFamily,
    [theme.breakpoints.down("md")]: {
      flexWrap: "wrap",
    },
    [theme.breakpoints.down("sm")]: {
      padding: "34px",
    },
  },
  nft_img_div: {
    marginTop: "20px",
    "& img": {
      width: "578px",
      [theme.breakpoints.down("sm")]: {
        width: "310px",
      },
    },
  },
  nft_details_div: {
    display: "flex",
    flexDirection: "column",
  },
  buyNft_title: {
    color: theme.palette.text.primary,
    fontSize: "32px",
    fontWeight: "700",
    marginBottom: "26.85px",
    [theme.breakpoints.down("sm")]: {
      fontSize: "24px",
      fontWeight: "500",
    },
  },
  buyNft_description: {
    fontSize: "14px",
    fontWeight: "500",
    opacity: "62%",
    marginBottom: "26.85px",
  },
  buyNft_description_para: {
    display: "inline",
    fontSize: "16px",
    fontWeight: "400",
    lineHeight: "1.5",
    [theme.breakpoints.down("sm")]: {
      fontSize: "13px",
    },
  },
  ShowMore_link: {
    color: theme.palette.icon.primary,
    cursor: "pointer",
  },
  buypage_quantity: {
    color: theme.palette.text.primary,
    display: "flex",
    justifyContent: "space-between",
    marginTop: "20.85px",
    marginBottom: "12.62px",
  },

  buypage_quan_cont: {
    fontSize: "14px",
    fontWeight: "700",
    [theme.breakpoints.down("sm")]: {
      fontWeight: "500",
    },
  },
}));
